#define PVRSRV_MODULE_BASEDIR "/system/modules/"
#define LINUX 
#define PVR_BUILD_DIR "xb4780_android"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 540
#define SGX540 
#define SUPPORT_SGX540 
#define SUPPORT_SGX 
#define SGX_CORE_REV 130
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define USE_PTHREADS 
#define DISPLAY_CONTROLLER dc_xblfb
#define _XOPEN_SOURCE 600
#define _POSIX_C_SOURCE 199309
#define OPK_DEFAULT "libpvrANDROID_WSEGL.so"
#define OPK_FALLBACK ""
#define FFGEN_UNIFLEX 
#define SUPPORT_OPENCL 
#define SUPPORT_RSCOMPUTE 
#define EGL_EXTENSION_IMG_CL_IMAGE 
#define RELEASE 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_FEATURE_SYSTEM_CACHE 
#define PVRSRV_USSE_EDM_STATUS_DEBUG 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define SUPPORT_PVRSRV_DEVICE_CLASS 
#define IMG_ADDRSPACE_PHYSADDR_BITS 32
#define PVR2D_ALT_2DHW 
#define PVR2D_VALIDATE_INPUT_PARAMS 
#define SUPPORT_OPENGLES1 
#define SUPPORT_OPENGLES2 
#define SUPPORT_OPENGLES1_V1_ONLY 
#define SUPPORT_OPENGL 
#define SUPPORT_OPENCL_11 
#define SUPPORT_SOURCE_SHADER 
#define SUPPORT_BINARY_SHADER 
#define CLIENT_DRIVER_DEFAULT_WAIT_RETRIES 50
#define API_MODULES_RUNTIME_CHECKED 
#define FORCE_ENABLE_GROW_SHRINK 
#define EGL_EXTENSION_ANDROID_RECORDABLE 
#define EGL_EXTENSION_ANDROID_BLOB_CACHE 
#define EGL_EXTENSION_ANDROID_FRAMEBUFFER_TARGET 
#define EGL_EXTENSION_ANDROID_NATIVE_FENCE_SYNC 
#define GLES1_EXTENSION_EGL_IMAGE_EXTERNAL 
#define GLES2_EXTENSION_EGL_IMAGE_EXTERNAL 
#define GLES2_EXTENSION_UBO 
#define ION_DEFAULT_HEAP_ID_MASK ION_HEAP_SYSTEM_MASK
#define ANDROID 
#define OGLES1_BASEPATH "/system/vendor/lib/egl/"
#define OGLES2_BASEPATH "/system/vendor/lib/egl/"
#define OGLES1_BASENAME "GLESv1_CM_POWERVR_SGX540_130"
#define OGLES2_BASENAME "GLESv2_POWERVR_SGX540_130"
#define SUPPORT_GRAPHICS_HAL 
#define SUPPORT_ANDROID_PLATFORM 
#define SUPPORT_ANDROID_MEMTRACK_HAL 
#define PVR_ANDROID_USE_WINDOW_TRANSFORM_HINT 
#define PVR_ANDROID_PLATFORM_HAS_LINUX_FBDEV 
#define PVR_ANDROID_HAS_HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED 
#define PVR_ANDROID_HAS_HAL_PIXEL_FORMAT_BLOB 
#define PVR_ANDROID_HAS_HAL_PIXEL_FORMAT_Y16 
#define PVR_ANDROID_HAS_HAL_PIXEL_FORMAT_Y8 
#define PVR_ANDROID_HAS_HAL_PIXEL_FORMAT_YCbCr_420_888 
#define PVR_ANDROID_HAS_GRALLOC_USAGE_HW_CAMERA 
#define PVR_ANDROID_HAS_GRALLOC_USAGE_CURSOR 
#define PVR_ANDROID_REMAP_HW_ONLY_PIXEL_FORMATS 
#define PVR_ANDROID_HWC_HAS_1_3_FEATURES 
#define PVR_ANDROID_RELAX_GRALLOC_MODULE_MAP_CHECKS 
#define PVR_ANDROID_CAMERA_ACTIVE_ARRAY_SIZE_HAS_XMIN_YMIN 
#define PVR_ANDROID_CAMERA_CONTROL_MAX_REGIONS_HAS_THREE 
#define PVR_ANDROID_GRALLOC_HAS_0_2_FEATURES 
#define PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC 
